# Generated by Django 5.2.8 on 2025-11-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarity_app', '0003_task_parent_task_aimemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimemory',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aimemory',
            name='ai_summary_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
