# Generated by Django 5.2.8 on 2025-11-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarity_app', '0004_aimemory_ai_summary_aimemory_ai_summary_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
