# Generated by Django 5.2.8 on 2025-11-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarity_app', '0005_task_calendar_event_id_task_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
